# Generated by Django 3.1.7 on 2021-03-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='block_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.IntegerField()),
                ('block_name', models.CharField(max_length=50)),
                ('block_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='district_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField()),
                ('district_name', models.CharField(max_length=50)),
                ('district_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='panchayat_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=25)),
                ('descrp', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=250)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='panchayat_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('panchayat_name', models.CharField(max_length=50)),
                ('panchayat_code', models.CharField(max_length=10)),
                ('addr', models.CharField(max_length=500)),
                ('pin', models.CharField(max_length=25)),
                ('pre_name', models.CharField(max_length=50)),
                ('pre_contact', models.CharField(max_length=25)),
                ('pre_email', models.CharField(max_length=250)),
                ('sec_name', models.CharField(max_length=50)),
                ('sec_contact', models.CharField(max_length=25)),
                ('sec_email', models.CharField(max_length=250)),
                ('ward_count', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='panchayat_user_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
                ('remarks', models.CharField(max_length=500)),
                ('rdt', models.CharField(max_length=25)),
                ('rtm', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='state_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50)),
                ('state_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ward_member_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('panchayat_id', models.IntegerField()),
                ('ward_no', models.CharField(max_length=10)),
                ('member_name', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=500)),
                ('pin', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ward_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('ward_no', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('descrp', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=250)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ward_news_user_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_news_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('remarks', models.CharField(max_length=250)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ward_user_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('ward_no', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
                ('remarks', models.CharField(max_length=500)),
                ('rdt', models.CharField(max_length=25)),
                ('rtm', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='age',
            new_name='district_id',
        ),
        migrations.AddField(
            model_name='user_details',
            name='aadhaar_no',
            field=models.CharField(default='ok', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='dob',
            field=models.CharField(default='ok', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='house_no',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='panchayat_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='state_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='status',
            field=models.CharField(default='ok', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='ward_no',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_details',
            name='contact',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='lname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='pin',
            field=models.CharField(max_length=25),
        ),
    ]
