# Generated by Django 3.1.7 on 2021-04-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210309_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ward_covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('ward_no', models.CharField(max_length=25)),
                ('poscase', models.CharField(max_length=25)),
                ('negcase', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
