# Generated by Django 3.1.6 on 2021-05-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_ward_covid'),
    ]

    operations = [
        migrations.CreateModel(
            name='liscence_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('descp', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='taxcollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panchayat_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('houseno', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=500)),
                ('cvv', models.CharField(max_length=500)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
            ],
        ),
    ]
