# Generated by Django 3.1.6 on 2021-05-31 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_liscence_request_taxcollection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='liscence_request',
            new_name='licence_request',
        ),
    ]
